config:
    # in distribution dataset
    id_dataset: "cifar10"
    # out-of-distribution datasets
    ood_datasets: ["lsuncrop", "lsunresize", "isun", "textures"]
    # model
    model_name: "densenet100"
    # path to checkpoint from which to be restored
    train_restore_file: "densenet100_cifar10.pth"
    # batch size
    batch_size: 200
    # scoring method
    scoring_method: "energy"
    # method
    method: "ash_s@50"
